#!/usr/bin/env python3
"""Helpers for the USB iPhone installer. Safe to import from tests."""

from __future__ import annotations

import argparse
import json
import plistlib
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

TEAM_ID_RE = re.compile(r"^[A-Z0-9]{6,12}$")
BUNDLE_ID_RE = re.compile(r"^[A-Za-z][A-Za-z0-9-]*(\.[A-Za-z][A-Za-z0-9-]*)+$")
ENV_KEYS = ("DEVELOPMENT_TEAM", "PRODUCT_BUNDLE_IDENTIFIER", "DEVICE_UDID")
XCODE_PREFS = Path.home() / "Library/Preferences/com.apple.dt.Xcode.plist"


def suggest_bundle_id(team_id: str) -> str:
    token = re.sub(r"[^A-Za-z0-9]", "", team_id or "").lower()
    if not token:
        return "com.local.receiptsync"
    return f"com.receiptsync.t{token}"


def parse_local_env(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key in ENV_KEYS:
            values[key] = value.strip().strip("\"'")
    return values


def read_local_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    return parse_local_env(path.read_text(encoding="utf-8"))


def write_local_env(path: Path, team: str, bundle: str, device: str = "") -> None:
    if not TEAM_ID_RE.match(team):
        raise ValueError("DEVELOPMENT_TEAM must be a 6-12 character Apple team id")
    if not BUNDLE_ID_RE.match(bundle):
        raise ValueError("PRODUCT_BUNDLE_IDENTIFIER is not a valid reverse-DNS id")
    if device and not re.match(r"^[A-Za-z0-9-]+$", device):
        raise ValueError("DEVICE_UDID contains unsupported characters")
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by ios/install-iphone.sh. Do not commit this file.",
        f"DEVELOPMENT_TEAM={team}",
        f"PRODUCT_BUNDLE_IDENTIFIER={bundle}",
    ]
    if device:
        lines.append(f"DEVICE_UDID={device}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_pbxproj_team_ids(text: str) -> list[str]:
    found: list[str] = []
    for match in re.finditer(r"DEVELOPMENT_TEAM\s*=\s*([A-Z0-9]{6,12})\s*;", text):
        team_id = match.group(1)
        if team_id not in found:
            found.append(team_id)
    return found


def parse_certificate_subjects(text: str) -> list[str]:
    found: list[str] = []
    for match in re.finditer(r"\bOU=([A-Z0-9]{6,12})\b", text):
        team_id = match.group(1)
        if team_id not in found:
            found.append(team_id)
    for match in re.finditer(r"Apple Development:[^(\n]+ \(([A-Z0-9]{6,12})\)", text):
        team_id = match.group(1)
        if team_id not in found:
            found.append(team_id)
    return found


def _team_from_mapping(item: Any) -> tuple[str, str] | None:
    if not isinstance(item, dict):
        return None
    team_id = str(
        item.get("teamID")
        or item.get("identifier")
        or item.get("teamId")
        or item.get("teamIdentifier")
        or ""
    ).strip()
    if not TEAM_ID_RE.match(team_id):
        return None
    label = str(item.get("teamName") or item.get("name") or item.get("teamType") or "").strip()
    if not label:
        label = "Personal Team"
    elif "personal" in label.lower() or item.get("teamType") == "Personal Team":
        label = "Personal Team"
    else:
        label = re.sub(r"\S+@\S+", "Personal Team", label)
        if "@" in label:
            label = "Personal Team"
    return team_id, label


def parse_xcode_provisioning_teams(data: Any) -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add(item: Any) -> None:
        parsed = _team_from_mapping(item)
        if parsed and parsed[0] not in seen:
            seen.add(parsed[0])
            found.append(parsed)

    def add_from(root: Any) -> None:
        if isinstance(root, dict):
            parsed = _team_from_mapping(root)
            if parsed:
                add(root)
                return
            for value in root.values():
                add_from(value)
        elif isinstance(root, list):
            for item in root:
                add_from(item)
        else:
            add(root)

    if isinstance(data, dict) and (
        "IDEProvisioningTeams" in data or "IDEProvisioningTeamByIdentifier" in data
    ):
        for key in ("IDEProvisioningTeams", "IDEProvisioningTeamByIdentifier"):
            if key in data:
                add_from(data[key])
        return found
    add_from(data)
    return found


def is_physical_iphone(entry: dict[str, Any]) -> bool:
    if entry.get("simulator") is True:
        return False
    platform = str(
        entry.get("platform")
        or entry.get("hardwareProperties", {}).get("platform")
        or ""
    ).lower()
    model = str(
        entry.get("modelName")
        or entry.get("hardwareProperties", {}).get("deviceType")
        or entry.get("name")
        or entry.get("deviceProperties", {}).get("name")
        or ""
    ).lower()
    if "simulator" in model or "mac" in platform or "macos" in platform:
        return False
    if "iphoneos" in platform or platform == "ios":
        return "ipad" not in model
    return "iphone" in model and "ipad" not in model


def _iphone_from_xcdevice(entry: dict[str, Any]) -> dict[str, str] | None:
    if not is_physical_iphone(entry):
        return None
    udid = str(
        entry.get("identifier")
        or entry.get("hardwareProperties", {}).get("udid")
        or ""
    ).strip()
    name = str(
        entry.get("name")
        or entry.get("deviceProperties", {}).get("name")
        or entry.get("modelName")
        or "iPhone"
    ).strip()
    os_version = str(
        entry.get("operatingSystemVersion")
        or entry.get("deviceProperties", {}).get("osVersionNumber")
        or ""
    ).strip()
    available = entry.get("available")
    if available is None:
        transport = str(entry.get("connectionProperties", {}).get("transportType") or "").lower()
        available = transport in {"wired", "local", "usb"} or bool(
            entry.get("connectionProperties", {}).get("tunnelState")
        )
    if not udid:
        return None
    return {
        "udid": udid,
        "name": name,
        "os": os_version,
        "available": "1" if available else "0",
    }


def parse_xcdevice_list(payload: Any) -> list[dict[str, str]]:
    entries: list[Any]
    if isinstance(payload, list):
        entries = payload
    elif isinstance(payload, dict):
        result = payload.get("result", payload)
        entries = result.get("devices") or result.get("result") or []
        if isinstance(entries, dict):
            entries = list(entries.values())
    else:
        return []
    phones: list[dict[str, str]] = []
    seen: set[str] = set()
    for item in entries:
        if not isinstance(item, dict):
            continue
        phone = _iphone_from_xcdevice(item)
        if phone and phone["udid"] not in seen:
            seen.add(phone["udid"])
            phones.append(phone)
    return phones


def parse_xctrace_devices(text: str) -> list[dict[str, str]]:
    phones: list[dict[str, str]] = []
    in_devices = False
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if line == "== Devices ==":
            in_devices = True
            continue
        if line.startswith("== ") and line.endswith(" =="):
            in_devices = False
            continue
        if not in_devices or not line:
            continue
        lowered = line.lower()
        if "macbook" in lowered or "mac mini" in lowered or "imac" in lowered or "my mac" in lowered:
            continue
        if "iphone" not in lowered:
            continue
        match = re.search(r"\(([0-9A-Fa-f-]{16,})\)(?:\s+\(([^)]+)\))?$", line)
        if not match:
            continue
        name = line[: match.start()].strip()
        phones.append(
            {
                "udid": match.group(1),
                "name": name or "iPhone",
                "os": (match.group(2) or "").strip(),
                "available": "1",
            }
        )
    return phones


def _run_json(command: list[str]) -> Any | None:
    try:
        output = subprocess.check_output(command, stderr=subprocess.DEVNULL, text=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    try:
        return json.loads(output)
    except json.JSONDecodeError:
        return None


def discover_iphones() -> list[dict[str, str]]:
    payload = _run_json(["xcrun", "xcdevice", "list"])
    phones = parse_xcdevice_list(payload) if payload is not None else []
    if phones:
        return phones
    try:
        text = subprocess.check_output(
            ["xcrun", "xctrace", "list", "devices"],
            stderr=subprocess.STDOUT,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return []
    return parse_xctrace_devices(text)


def _certificate_subjects() -> str:
    try:
        pems = subprocess.check_output(
            ["security", "find-certificate", "-a", "-c", "Apple Development", "-p"],
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return ""
    if not pems:
        return ""
    subjects: list[str] = []
    current: list[bytes] = []
    for line in pems.splitlines(keepends=True):
        current.append(line)
        if b"END CERTIFICATE" in line:
            block = b"".join(current)
            current = []
            try:
                subject = subprocess.check_output(
                    ["openssl", "x509", "-noout", "-subject"],
                    input=block,
                    stderr=subprocess.DEVNULL,
                ).decode("utf-8", "replace")
            except (OSError, subprocess.CalledProcessError):
                continue
            subjects.append(subject)
    return "\n".join(subjects)


def discover_teams(pbxproj: Path | None = None, env_path: Path | None = None) -> list[tuple[str, str, str]]:
    found: list[tuple[str, str, str]] = []
    seen: set[str] = set()

    def add(team_id: str, label: str, source: str) -> None:
        team_id = team_id.strip()
        if not TEAM_ID_RE.match(team_id) or team_id in seen:
            return
        seen.add(team_id)
        found.append((team_id, label, source))

    if env_path:
        env = read_local_env(env_path)
        if env.get("DEVELOPMENT_TEAM"):
            add(env["DEVELOPMENT_TEAM"], "Saved installer setting", "env")
    if pbxproj and pbxproj.is_file():
        for team_id in parse_pbxproj_team_ids(pbxproj.read_text(encoding="utf-8", errors="replace")):
            add(team_id, "Xcode project", "pbxproj")
    if XCODE_PREFS.is_file():
        try:
            data = plistlib.loads(XCODE_PREFS.read_bytes())
        except Exception:
            data = {}
        for team_id, label in parse_xcode_provisioning_teams(data):
            add(team_id, label, "xcode")
    for team_id in parse_certificate_subjects(_certificate_subjects()):
        add(team_id, "Apple Development certificate", "certificate")
    return found


def _print_iphones(phones: list[dict[str, str]]) -> None:
    for phone in phones:
        print(f"{phone['udid']}\t{phone['name']}\t{phone['os']}\t{phone['available']}")


def _print_teams(teams: list[tuple[str, str, str]]) -> None:
    for team_id, label, source in teams:
        print(f"{team_id}\t{label}\t{source}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="ReceiptSync iPhone installer helpers")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("list-iphones")
    teams_parser = sub.add_parser("list-teams")
    teams_parser.add_argument("--pbxproj")
    teams_parser.add_argument("--env")
    bundle_parser = sub.add_parser("suggest-bundle")
    bundle_parser.add_argument("team_id")
    dump_parser = sub.add_parser("dump-env")
    dump_parser.add_argument("path")
    env_parser = sub.add_parser("write-env")
    env_parser.add_argument("path")
    env_parser.add_argument("--team", required=True)
    env_parser.add_argument("--bundle", required=True)
    env_parser.add_argument("--device", default="")
    args = parser.parse_args(argv)

    if args.command == "list-iphones":
        _print_iphones(discover_iphones())
        return 0
    if args.command == "list-teams":
        _print_teams(
            discover_teams(
                Path(args.pbxproj) if args.pbxproj else None,
                Path(args.env) if args.env else None,
            )
        )
        return 0
    if args.command == "suggest-bundle":
        print(suggest_bundle_id(args.team_id))
        return 0
    if args.command == "dump-env":
        for key, value in read_local_env(Path(args.path)).items():
            print(f"{key}={value}")
        return 0
    write_local_env(Path(args.path), args.team, args.bundle, args.device)
    return 0


if __name__ == "__main__":
    sys.exit(main())
